<div class="left-side mt-4">
    <div class="float-start">
        <?php if ($sc['page'] == "chat") { ?>
            <a data-bs-toggle="tooltip" title="Go Back" href="<?php echo Sh_Link('dashboard'); ?>" class="myDislink">
                <i class="fa fa-backward fs-4 me-4"></i>
            </a>
        <?php } ?>
        
        <a data-bs-toggle="modal" href="#settingsmodal" role="button" data-bs-toggle="tooltip" title="Settings" class="myDislink">
            <i class="fa fa-sliders fs-4"></i>
        </a>
        
        
        <!-- <i class="fa fa-backward fs-4 me-2"></i> -->
    </div>
</div>


<div class="middle mx-auto">
    <div class="avartar float-start">
        <img src="<?= $sc['user']['avartar'] ?>" class="img-fluid img-thumbnail rounde-5 avartar-img" alt="" srcset="">
    </div>

    <div class="float-start mt-1 ms-2">
        <a href="<?php echo Sh_Link('dashboard'); ?>" class="myDislink">
            <h5 class="fs-5"><?= $sc['user']['name'] ?></h5>
        </a>
        <h6><i class="fa fa-circle-dot text-success"></i> Active</h6>
    </div>
</div>



<div class="float-end right-side ms-auto mt-4">
    <a class="myDislink" data-bs-toggle="tooltip" title="LogOut" href="<?php echo Sh_Link('logout'); ?>">
        <i class="fa fa-right-from-bracket fs-4"></i>
    </a>
</div>