<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $sc['title'] ?></title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <!-- custom css -->
        <link rel="stylesheet" href="assets/css/main.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

        <script>
          function Sh_Ajax_Requests_File(){
            return "<?php echo $sc['config']['site_url'].'/requests.php';?>"
          }
        </script>
    </head>
    <body>

        <div class="container">
            <div class="row align-items-center justify-content-center vh-100">
                <div class="col-md-8 mx-auto">

                    <?= $sc['content'] ?>

                </div>
            </div>
        </div>
    </body>

    
</html>


<?php foreach ( $sc['user_msg']['conversation'] as $message ) { ?>

<?php if ( $message['from_id'] == $sc['user_msg']['user_id'] ) { ?>
    <div class="msg-out w-100 mb-3 float-start">
        <div class="msg-avartar float-start">
            <img src="<?= $sc['user_msg']['avartar'] ?>" class="img-fluid img-thumbnail rounde-5 avartar-img" alt="" srcset="">
        </div>
        <div class="msg-body px-3 float-start ms-2">
            <div class="ms-1">
                <p class="name"><?= $sc['user_msg']['name'] ?></p>
                <p class="msg"><?= $message['message'] ?></p>
            </div>    
        </div>
        <div class="msg-time w-100 ms-5 px-3 float-start ">
            <p class="time float-start"><i>1 min ago</i></p>
        </div>
    </div>
<?php }else{ ?>
    <div class="msg-in w-100 mb-2 float-end">
        <div class="msg-avartar float-end">
            <img src="<?= $sc['user']['avartar'] ?>" class="img-fluid img-thumbnail rounde-5 avartar-img" alt="" srcset="">
        </div>
        <div class="msg-in-body px-3 float-end me-2">
            <div class="ms-1">
                <p class="name"><?= $sc['user']['name'] ?></p>
                <p class="msg"><?= $message['message'] ?></p>
            </div>
        </div>
        <div class="msg-in-time w-100 me-5 px-3 float-end">
            <p class="time float-end"><i>1 min ago</i></p>
        </div>
    </div>
<?php } ?>

<?php } ?>