<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <!-- custom css -->
        <link rel="stylesheet" href="assets/css/main.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script>
          function Sh_Ajax_Requests_File(){
            return "<?php echo $sc['config']['site_url'].'/requests.php';?>"
          }
        </script>
    </head>
    <body>

        <div class="container">
            <div class="row align-items-center justify-content-center vh-100">
                <div class="col-md-10 mx-auto">

                <?= $sc['content'] ?>

                </div>
            </div>
        </div>
    </body>
    <script type="text/javascript">

    

    // Registration script
    $("#reg-form").on('submit',(function(e) {
      e.preventDefault();
      $.ajax({
         url: Sh_Ajax_Requests_File() + '?f=register&s=submit_register',
         type: "POST",
         data:  new FormData(this),
         contentType: false,
         cache: false,
         processData:false,
       beforeSend : function() {
        $("#reg-btn").attr('disabled', true);
       },
       success: function(data) {

         $("#reg-btn").attr('disabled', false);

          if(data.status == 200) {
            $("#reg-form")[0].reset();
            $("#error").removeClass("alert alert-danger").addClass("alert alert-success").text(data.message);
          } else {
            $("#error").removeClass("alert alert-success").addClass("alert alert-danger").text(data.errors);
          }

        },
         error: function(e) {
           $("#error").html(e).fadeIn();
         }
        });
      }));


      // Login
      $("#login-form").on('submit',(function(e) {
      e.preventDefault();

      var formData = {
        username: $("#email").val(),
        password: $("#password").val()
      };

      $.ajax({
         url: Sh_Ajax_Requests_File() + '?f=login',
         type: "POST",
         data: formData,
         dataType: "json",
         encode: true,
       beforeSend : function() {
        $("#login-btn").attr('disabled', true);
       },
       success: function(data) {

         $("#login-btn").attr('disabled', false);

          if(data.status == 200) {

            $("#login-form")[0].reset();
            $("#login-form").addClass("d-none");
            $("#error").removeClass("alert alert-danger").addClass("alert alert-success").html(data.message);
            
            setTimeout(function () {
              window.location.href = data.location;
            }, 1000);

          } else {
            $("#error").removeClass("alert alert-success").addClass("alert alert-danger").html(data.errors);
          }

        }
        });
      }));

    </script>
</html>